#!/bin/bash
#
# OpenClaw Setup Wizard
# Run this AFTER the silent install to configure everything in one go
#
# Usage:
#   ~/.openclaw/workspace/scripts/setup.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/../config/config-optimal-defaults.json"
ENV_FILE="$WORKSPACE/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║${NC}              🦞 OpenClaw Setup Wizard                      ${BLUE}║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# =============================================================================
# Collect Information
# =============================================================================

echo -e "${BOLD}Let's get you set up. I'll ask for a few API keys.${NC}"
echo ""

# --- Anthropic (Required) ---
echo -e "${CYAN}1. Anthropic API Key ${RED}(required)${NC}"
echo "   This powers Claude - the brain of your agent."
echo "   Get one at: https://console.anthropic.com"
echo ""
read -p "   Enter your Anthropic API key: " ANTHROPIC_KEY

if [ -z "$ANTHROPIC_KEY" ]; then
  echo -e "${RED}Error: Anthropic key is required${NC}"
  exit 1
fi

# --- Channel Selection ---
echo ""
echo -e "${CYAN}2. Messaging Channel${NC}"
echo "   How will you talk to your agent?"
echo ""
echo "   1) Telegram (easiest)"
echo "   2) Discord"
echo ""
read -p "   Choose [1/2]: " CHANNEL_CHOICE

case $CHANNEL_CHOICE in
  1)
    CHANNEL="telegram"
    echo ""
    echo "   Get a bot token from @BotFather on Telegram:"
    echo "   Message @BotFather → /newbot → follow prompts → copy token"
    echo ""
    read -p "   Enter your Telegram bot token: " BOT_TOKEN
    ;;
  2)
    CHANNEL="discord"
    echo ""
    echo "   Get a bot token from Discord Developer Portal:"
    echo "   https://discord.com/developers/applications"
    echo ""
    read -p "   Enter your Discord bot token: " BOT_TOKEN
    ;;
  *)
    echo -e "${RED}Invalid choice${NC}"
    exit 1
    ;;
esac

if [ -z "$BOT_TOKEN" ]; then
  echo -e "${RED}Error: Bot token is required${NC}"
  exit 1
fi

# --- Gemini (Optional but recommended) ---
echo ""
echo -e "${CYAN}3. Gemini API Key ${GREEN}(free, recommended)${NC}"
echo "   Powers RAG memory and cheap AI tasks."
echo "   Get one at: https://aistudio.google.com/apikey"
echo ""
read -p "   Enter your Gemini API key (or press Enter to skip): " GEMINI_KEY

# --- DeepSeek (Optional) ---
echo ""
echo -e "${CYAN}4. DeepSeek API Key ${YELLOW}(optional, ~\$0.14/M tokens)${NC}"
echo "   Cheap coding workhorse for building tools."
echo "   Get one at: https://platform.deepseek.com"
echo ""
read -p "   Enter your DeepSeek API key (or press Enter to skip): " DEEPSEEK_KEY

# --- Aider (Optional) ---
echo ""
echo -e "${CYAN}5. Install Aider? ${YELLOW}(optional)${NC}"
echo "   Aider is a powerful AI coding assistant that works with DeepSeek."
echo "   Great for multi-file edits, git-aware, auto-commits."
echo ""
read -p "   Install Aider? [y/N]: " INSTALL_AIDER

# =============================================================================
# Apply Configuration
# =============================================================================

echo ""
echo -e "${BLUE}[openclaw]${NC} Applying configuration..."

# --- Write .env file ---
cat > "$ENV_FILE" << EOF
# OpenClaw Workspace Tools
# Generated by setup.sh

# Gemini API (FREE!) - for RAG embeddings
GEMINI_API_KEY=$GEMINI_KEY

# DeepSeek API - for cheap coding
DEEPSEEK_API_KEY=$DEEPSEEK_KEY

# Brave Search API - for web search (add later if needed)
BRAVE_API_KEY=
EOF

echo -e "${GREEN}[✓]${NC} Created .env file"

# --- Run openclaw init non-interactively ---
# Create the config directly since openclaw init is interactive

OPENCLAW_CONFIG="$HOME/.openclaw/openclaw.json"
mkdir -p "$HOME/.openclaw"

if [ "$CHANNEL" = "telegram" ]; then
  cat > "$OPENCLAW_CONFIG" << EOF
{
  "anthropic": {
    "apiKey": "$ANTHROPIC_KEY"
  },
  "channels": {
    "telegram": {
      "enabled": true,
      "botToken": "$BOT_TOKEN"
    }
  },
  "agents": {
    "defaults": {
      "model": "anthropic/claude-sonnet-4"
    }
  }
}
EOF
else
  cat > "$OPENCLAW_CONFIG" << EOF
{
  "anthropic": {
    "apiKey": "$ANTHROPIC_KEY"
  },
  "channels": {
    "discord": {
      "enabled": true,
      "botToken": "$BOT_TOKEN"
    }
  },
  "agents": {
    "defaults": {
      "model": "anthropic/claude-sonnet-4"
    }
  }
}
EOF
fi

echo -e "${GREEN}[✓]${NC} Created OpenClaw config"

# --- Apply optimal config ---
node -e "
const fs = require('fs');
const path = require('path');

const configPath = '$OPENCLAW_CONFIG';
const patchPath = '$CONFIG_FILE';

const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const patch = JSON.parse(fs.readFileSync(patchPath, 'utf8'));

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      target[key] = target[key] || {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const merged = deepMerge(config, patch);
fs.writeFileSync(configPath, JSON.stringify(merged, null, 2));
"

echo -e "${GREEN}[✓]${NC} Applied optimal settings (memory search, heartbeat, etc.)"

# --- Install Aider if requested ---
if [[ "$INSTALL_AIDER" =~ ^[Yy]$ ]]; then
  echo -e "${BLUE}[openclaw]${NC} Installing Aider..."
  pip install aider-chat 2>/dev/null || pip3 install aider-chat 2>/dev/null || {
    echo -e "${YELLOW}[!]${NC} Aider install failed (Python/pip required)"
    echo "    Install manually: pip install aider-chat"
  }
  
  if command -v aider &> /dev/null; then
    echo -e "${GREEN}[✓]${NC} Aider installed"
    
    # Add alias hint
    echo ""
    echo -e "${CYAN}Aider tip:${NC} Add this alias to use DeepSeek with Aider:"
    echo "    alias code='aider --model deepseek/deepseek-chat'"
  fi
fi

# =============================================================================
# Start Gateway
# =============================================================================

echo ""
echo -e "${BLUE}[openclaw]${NC} Starting gateway..."
echo ""

# Start in background
openclaw gateway start &
GATEWAY_PID=$!

sleep 3

if kill -0 $GATEWAY_PID 2>/dev/null; then
  echo -e "${GREEN}[✓]${NC} Gateway started"
else
  echo -e "${YELLOW}[!]${NC} Gateway may have failed to start"
  echo "    Check with: openclaw gateway status"
fi

# =============================================================================
# Done!
# =============================================================================

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║${NC}                    ✓ Setup Complete!                       ${GREEN}║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Your agent is ready!${NC}"
echo ""
if [ "$CHANNEL" = "telegram" ]; then
  echo "  👉 Open Telegram and message your bot"
else
  echo "  👉 Add your bot to a Discord server and message it"
fi
echo ""
echo -e "  ${CYAN}What happens next:${NC}"
echo "  Your agent will read BOOTSTRAP.md and guide you through"
echo "  personalization — choosing a name, personality, integrations."
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo "    openclaw gateway status   # Check if running"
echo "    openclaw gateway logs     # View logs"
echo "    openclaw gateway restart  # Restart"
echo ""
if [ -n "$DEEPSEEK_KEY" ] && [[ "$INSTALL_AIDER" =~ ^[Yy]$ ]]; then
  echo -e "  ${CYAN}Coding with Aider + DeepSeek:${NC}"
  echo "    export DEEPSEEK_API_KEY='$DEEPSEEK_KEY'"
  echo "    aider --model deepseek/deepseek-chat"
  echo ""
fi
